//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeranfuenMirrorSyncWcfClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISyncService")]
    public interface ISyncService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/RunSync", ReplyAction="http://tempuri.org/ISyncService/RunSyncResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.FileSyncActionStatus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.FileSyncActionStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.FileSyncAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.FileSyncAction.FileActionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.FileSyncActionStatus.ActionStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        void RunSync(string sourceRoot, string mirrorRoot, object[] fileFilters, object[] directoryFilters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/RunSync", ReplyAction="http://tempuri.org/ISyncService/RunSyncResponse")]
        System.Threading.Tasks.Task RunSyncAsync(string sourceRoot, string mirrorRoot, object[] fileFilters, object[] directoryFilters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/GetCurrentSyncStatus", ReplyAction="http://tempuri.org/ISyncService/GetCurrentSyncStatusResponse")]
        SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus GetCurrentSyncStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/GetCurrentSyncStatus", ReplyAction="http://tempuri.org/ISyncService/GetCurrentSyncStatusResponse")]
        System.Threading.Tasks.Task<SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus> GetCurrentSyncStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/GetHistorySyncStatus", ReplyAction="http://tempuri.org/ISyncService/GetHistorySyncStatusResponse")]
        SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus[] GetHistorySyncStatus(string sourceRoot, string mirrorRoot, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/GetHistorySyncStatus", ReplyAction="http://tempuri.org/ISyncService/GetHistorySyncStatusResponse")]
        System.Threading.Tasks.Task<SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus[]> GetHistorySyncStatusAsync(string sourceRoot, string mirrorRoot, int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncServiceChannel : SeranfuenMirrorSyncWcfClient.ServiceReference.ISyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncServiceClient : System.ServiceModel.ClientBase<SeranfuenMirrorSyncWcfClient.ServiceReference.ISyncService>, SeranfuenMirrorSyncWcfClient.ServiceReference.ISyncService {
        
        public SyncServiceClient() {
        }
        
        public SyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RunSync(string sourceRoot, string mirrorRoot, object[] fileFilters, object[] directoryFilters) {
            base.Channel.RunSync(sourceRoot, mirrorRoot, fileFilters, directoryFilters);
        }
        
        public System.Threading.Tasks.Task RunSyncAsync(string sourceRoot, string mirrorRoot, object[] fileFilters, object[] directoryFilters) {
            return base.Channel.RunSyncAsync(sourceRoot, mirrorRoot, fileFilters, directoryFilters);
        }
        
        public SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus GetCurrentSyncStatus() {
            return base.Channel.GetCurrentSyncStatus();
        }
        
        public System.Threading.Tasks.Task<SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus> GetCurrentSyncStatusAsync() {
            return base.Channel.GetCurrentSyncStatusAsync();
        }
        
        public SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus[] GetHistorySyncStatus(string sourceRoot, string mirrorRoot, int count) {
            return base.Channel.GetHistorySyncStatus(sourceRoot, mirrorRoot, count);
        }
        
        public System.Threading.Tasks.Task<SeranfuenMirrorSyncLib.Data.SourceMirrorSyncStatus[]> GetHistorySyncStatusAsync(string sourceRoot, string mirrorRoot, int count) {
            return base.Channel.GetHistorySyncStatusAsync(sourceRoot, mirrorRoot, count);
        }
    }
}
