//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeranfuenMirrorSync.StringResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeranfuenMirrorSync.StringResources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you wish to save the changes before closing?.
        /// </summary>
        public static string ConfirmSave_Message {
            get {
                return ResourceManager.GetString("ConfirmSave_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes.
        /// </summary>
        public static string ConfirmSave_Title {
            get {
                return ResourceManager.GetString("ConfirmSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The follow error occurred:
        ///
        ///{0}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error happened.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Sync Status.
        /// </summary>
        public static string GroupBox_LastStatus {
            get {
                return ResourceManager.GetString("GroupBox_LastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Syncs.
        /// </summary>
        public static string MainMenu_Edit {
            get {
                return ResourceManager.GetString("MainMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Run sync now.
        /// </summary>
        public static string MainMenu_RunNow {
            get {
                return ResourceManager.GetString("MainMenu_RunNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Last Status.
        /// </summary>
        public static string MainMenu_ShowLastStatus {
            get {
                return ResourceManager.GetString("MainMenu_ShowLastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination Folder.
        /// </summary>
        public static string MainScreen_LastStatus_DestinationFolder {
            get {
                return ResourceManager.GetString("MainScreen_LastStatus_DestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sync Duration.
        /// </summary>
        public static string MainScreen_LastStatus_Duration {
            get {
                return ResourceManager.GetString("MainScreen_LastStatus_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source Folder.
        /// </summary>
        public static string MainScreen_LastStatus_SourceFolder {
            get {
                return ResourceManager.GetString("MainScreen_LastStatus_SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Status.
        /// </summary>
        public static string MainScreen_LastStatus_Status {
            get {
                return ResourceManager.GetString("MainScreen_LastStatus_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual Sync.
        /// </summary>
        public static string ManualSync {
            get {
                return ResourceManager.GetString("ManualSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to conect to the sync service. Please make sure that it&apos;s running on your computer.
        /// </summary>
        public static string NoService_Error {
            get {
                return ResourceManager.GetString("NoService_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Service Running.
        /// </summary>
        public static string NoServiceRunning {
            get {
                return ResourceManager.GetString("NoServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service Running.
        /// </summary>
        public static string ServiceRunning {
            get {
                return ResourceManager.GetString("ServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The path &apos;{0}&apos; is already in the synchronization source.
        /// </summary>
        public static string SyncSourcesViewModel_AlreadyExistingPath_Message {
            get {
                return ResourceManager.GetString("SyncSourcesViewModel_AlreadyExistingPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path already exists.
        /// </summary>
        public static string SyncSourcesViewModel_AlreadyExistingPath_Title {
            get {
                return ResourceManager.GetString("SyncSourcesViewModel_AlreadyExistingPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An empty path cannot be added.
        /// </summary>
        public static string SyncSourcesViewModel_EmptyPath_Message {
            get {
                return ResourceManager.GetString("SyncSourcesViewModel_EmptyPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty path.
        /// </summary>
        public static string SyncSourcesViewModel_EmptyPath_Title {
            get {
                return ResourceManager.GetString("SyncSourcesViewModel_EmptyPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The path &apos;{0}&apos; you are trying to add does not seem to exist. Do you stil want to add it?.
        /// </summary>
        public static string SyncSourcesViewModel_PathNotExists_Message {
            get {
                return ResourceManager.GetString("SyncSourcesViewModel_PathNotExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path not found.
        /// </summary>
        public static string SyncSourcesViewModel_PathNotExists_Title {
            get {
                return ResourceManager.GetString("SyncSourcesViewModel_PathNotExists_Title", resourceCulture);
            }
        }
    }
}
